export const Questions = [
  "What movie can you rewatch over and over again?",
  "What song from your teenage years do you still listen to?",
  "What show on Netflix did you binge watch embarrassingly fast?",
  "What food could you not live without?",
  "What was your first job?",
  "What interesting skill do you want to learn?",
  "What did you want to be as a kid?",
  "What does your ideal day look like?",
  "What was the best and worst family trip?",
  "Who is the craziest family member?",
  "What's the best piece of advice that you've gotten from a family member?",
  "What is your favorite family tradition?",
  "How would you describe your family in 1 or 2 sentences?",
  "When was the last time you tried something new?",
  "What are you looking forward to the most this year?",
  "What can you do today that you were not capable of a year ago?",
  "What do you admire the most about yourself?",
  "What was the happiest moment in your life?",
  "If you could change one thing about the world, what would it be?",
  "If you won a lottery of $1 million, what would you do with all the money?",
  "What is the most useless talent you have?",
  "What is a random fact that you know that most people wouldn’t know?",
  "What is the most ridiculous thing you’ve tricked someone into believing?",
  "What is the silliest way that you’ve injured yourself?",
  "How long would you last in a zombie apocalypse?",
  "If you won a lottery of $1 million, what would you do with all the money?",
  "What’s the worst haircut you ever had?"
]
